conda_forge_output_validation: true

build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test_on_native_only: true

os_version:
  linux_64: cos7

azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: True
